cargo-features = ["per-package-target"]

[package]
name = "user-echo-svc"
version.workspace = true
edition.workspace = true
description = "V0.7 platform program (echo-svc)."
forced-target = "x86_64-unknown-none"

[dependencies]
ulib = { path = "../ulib" }

[[bin]]
name = "user-echo-svc"
path = "src/main.rs"
test = false
bench = false
