cargo-features = ["per-package-target"]

[package]
name = "user-fs-user-persist"
version.workspace = true
edition.workspace = true
forced-target = "x86_64-unknown-none"

[dependencies]
ulib = { path = "../ulib" }

[[bin]]
name = "user-fs-user-persist"
path = "src/main.rs"
test = false
bench = false
